steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-bot', '-f', 'Dockerfile.bot', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/telegram-dashboard', '-f', 'Dockerfile.dashboard', '.']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - telegram-bot
      - --image=gcr.io/$PROJECT_ID/telegram-bot
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=TELEGRAM_TOKEN=TELEGRAM_TOKEN:latest,GOOGLE_DRIVE_FOLDER_ID=GOOGLE_DRIVE_FOLDER_ID:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,GOOGLE_SERVICE_ACCOUNT_JSON=GOOGLE_SERVICE_ACCOUNT_JSON:latest,DASHBOARD_URL=DASHBOARD_URL:latest,ADMIN_IDS=ADMIN_IDS:latest
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - run
      - deploy
      - telegram-dashboard
      - --image=gcr.io/$PROJECT_ID/telegram-dashboard
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated
      - --set-secrets=GOOGLE_SERVICE_ACCOUNT_JSON=GOOGLE_SERVICE_ACCOUNT_JSON:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,DASHBOARD_PASS=DASHBOARD_PASS:latest
