name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Deploy Bot
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot --file Dockerfile.bot .
          gcloud run deploy telegram-bot             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-bot             --region ${{ secrets.GCP_REGION }}             --platform managed             --allow-unauthenticated             --set-secrets=TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest,GOOGLE_DRIVE_FOLDER_ID=GOOGLE_DRIVE_FOLDER_ID:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,GOOGLE_SERVICE_ACCOUNT_JSON=GOOGLE_SERVICE_ACCOUNT_JSON:latest,DASHBOARD_URL=WEBHOOK_URL:latest,ADMIN_IDS=ADMIN_IDS:latest

      - name: Deploy Dashboard
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-dashboard --file Dockerfile.dashboard .
          gcloud run deploy telegram-dashboard             --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/telegram-dashboard             --region ${{ secrets.GCP_REGION }}             --platform managed             --allow-unauthenticated             --set-secrets=GOOGLE_SERVICE_ACCOUNT_JSON=GOOGLE_SERVICE_ACCOUNT_JSON:latest,GOOGLE_SHEET_ID=GOOGLE_SHEET_ID:latest,DASHBOARD_PASS=DASHBOARD_PASS:latest
